### ISSUE TITLE
Not using banding variable?

### ISSUE THREAD

**Issue by rnowling** [karlhigley/spark-neighbors#25]
It seems the banding strategy is set to 10:

https://github.com/karlhigley/spark-neighbors/blob/master/src/main/scala/com/github/karlhigley/spark/neighbors/ANN.scala#L204

Should the `numBands` be used instead?

**Comment by karlhigley** [comment]
Absolutely, good catch! I'll make a fix.

**Comment by karlhigley** [comment]
I added a fix to be included in v0.2.0. If it's helpful, I can publish an 0.1.1 release.

**Comment by rnowling** [comment]
I can build a local version.  Thank you!
